

INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (37,'Vulpix','Fire');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (6,'Charizard','Fire');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (126,'Magmar','Fire');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (154,'Cyndaquil','Fire');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (653,'Fennekin','Fire');


INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (134,'Vaporeon','Water');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (55,'Golduck','Water');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (99,'Kingler','Water');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (129,'Magikarp','Water');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (131,'Lapras','Water');


INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (1,'Bulbasaur','Grass');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (071,'Victreebel','Grass');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (152,'Chikorita','Grass');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (192,'Sunflora','Grass');
INSERT INTO POKEMON (ID,NAME,TYPE) VALUES (319,'Sharpedo','Grass');

INSERT INTO TRAINER (TID,NAME,LEVEL) VALUES (1,'Arie',0);
INSERT INTO TRAINER (TID,NAME,LEVEL) VALUES (2,'Neo',0);
INSERT INTO TRAINER (TID,NAME,LEVEL) VALUES (3,'Trinity',0);
INSERT INTO TRAINER (TID,NAME,LEVEL) VALUES (4,'Smith',0);
INSERT INTO TRAINER (TID,NAME,LEVEL) VALUES (5,'Morpheus',0);

INSERT INTO BAG (TID,PID1,PID2,PID3) VALUES (1,1,131,653);
INSERT INTO BAG (TID,PID1,PID2,PID3) VALUES (2,6,71,129);
INSERT INTO BAG (TID,PID1,PID2,PID3) VALUES (3,55,99,129);
INSERT INTO BAG (TID,PID1,PID2) VALUES (4,319,134);
INSERT INTO BAG (TID) VALUES (5);

