CREATE TABLE POKEMON
(
    ID INT NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    TYPE VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TRAINER
(
    NAME VARCHAR(25) NOT NULL,
    LEVEL INT NOT NULL,
    TID INT NOT NULL,
    PRIMARY KEY (TID)
);


CREATE TABLE BAG
(
    TID INT NOT NULL,
    PID1 INT,
    PID2 INT,
    PID3 INT,
    PRIMARY KEY (TID),
    FOREIGN KEY (TID) REFERENCES TRAINER(TID),
    FOREIGN KEY (PID1) REFERENCES POKEMON(ID),
    FOREIGN KEY (PID2) REFERENCES POKEMON(ID),
    FOREIGN KEY (PID3) REFERENCES POKEMON(ID)
);
